### ISSUE TITLE
dante and dante_ltr error

### ISSUE THREAD

**Issue by hidvegin** [kavonrtep/dante_ltr#8]
Hello!

I have got a de novo genome assembly from Illumina PE sequencing. This assembly has got 8.7 million scaffolds in fasta format. I splitted this fasta file to multiple fasta files. One fasta file has got 400.000 scaffolds. I would like to analyze these multiple fasta files with `dante` and `dante_ltr`.  I got an error from `dante`:
```
Traceback (most recent call last):
  File "/home/fk8jybr/miniconda3/envs/dante/bin/dante", line 518, in <module>
    tmp_gff=recalculate_gff3_back_to_original_coordinates(args_part.domain_gff,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fk8jybr/miniconda3/envs/dante/bin/dante", line 298, in recalculate_gff3_back_to_original_coordinates
    real_chunk_size = get_original_header_and_coordinates(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fk8jybr/miniconda3/envs/dante/bin/dante", line 241, in get_original_header_and_coordinates
    real_chunk_size = matching_table_part[0][3] - matching_table_part[0][2]
                      ~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
I used this code for `dante`:

```
dante -D Viridiplantae_v3.0 \
 -o split0.gff3 \
 -dir /dante \
 -c 60 -q split0.fasta
```

How can I resolve this error? The 400.000 scaffolds are too much for `dante`? Should I decrease them?

**Comment by kavonrtep** [comment]
do think you can share you data with me so I can reproduce this error?
